### ISSUE TITLE
Pip refuses to install dependencies.

### ISSUE THREAD

**Issue by explasion** [JakeMakesStuff/DCustomRPC#19]
**Describe the bug**
Using Python for Windows version 3.7.150.1013 and pip version 18.0

**To Reproduce**
1. Go to 'DCustomRPC'
2. Right click in the folder.
3. Click on 'Git Bash Here or Command Prompt Here'
4. Use the install command: 'py -m pip install -r requirements.txt'

**Expected behavior**
Pip to install prerequisites.

**Screenshots**
https://puu.sh/B30q0/7049a7463f.png

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser Chrome
 - Version 67.0.3396.99

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 5
 - OS: Android 7.0 Nougat
 - Browser Chrome
 - Version 67.0.3396.87

**Additional context**
N/A

**Comment by JakeMakesStuff** [comment]
Try running it in Powershell as opposed to Git Bash since I don't know if Git Bash enforces a lower version of python.

**Comment by explasion** [comment]
https://puu.sh/B31me/e55bde7cfe.png
https://puu.sh/B31n7/772f1e7935.png
Nope. Is it incompatible with python 3.7?

**Comment by JakeMakesStuff** [comment]
Fixed over Discord.
